# Data Analysis on Titanic Dataset

In [219]:
%config IPCompiler.greedy = True

In [220]:
import pandas as pd
import numpy as np

In [221]:
dataset = pd.read_csv("train.csv") 

In [222]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [223]:
dataset.shape

(891, 12)

In [224]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [225]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [226]:
dataset.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

# Relationship between Target Column "Survived" and Other Features

In [227]:
dataset[['Pclass','Survived']].groupby('Pclass',as_index=False).sum()

Pclass  Survived
0       1       136
1       2        87
2       3       119

In [228]:
dataset[['Pclass','Survived']].groupby('Pclass',as_index=False).mean()

Pclass  Survived
0       1  0.629630
1       2  0.472826
2       3  0.242363

In [229]:
# people in ticket class 1 has more percentage of survival than people in ticket class 2 and 3 

In [230]:
dataset[['Sex','Survived']].groupby('Sex',as_index=False).sum()

Sex  Survived
0  female       233
1    male       109

In [231]:
dataset[['Sex','Survived']].groupby('Sex',as_index=False).mean()

Sex  Survived
0  female  0.742038
1    male  0.188908

In [232]:
# the percentage survival of women are much more than men.

In [233]:
dataset.Age.agg(['max','min','mean','median'])

max       80.000000
min        0.420000
mean      29.699118
median    28.000000
Name: Age, dtype: float64

In [234]:
dataset[['Age','Survived']].groupby('Age',as_index=False).sum()

Age  Survived
0    0.42         1
1    0.67         1
2    0.75         2
3    0.83         2
4    0.92         1
..    ...       ...
83  70.00         0
84  70.50         0
85  71.00         0
86  74.00         0
87  80.00         1

[88 rows x 2 columns]

In [235]:
dataset[['SibSp','Survived']].groupby('SibSp',as_index=False).sum()

SibSp  Survived
0      0       210
1      1       112
2      2        13
3      3         4
4      4         3
5      5         0
6      8         0

In [236]:
dataset[['SibSp','Survived']].groupby('SibSp',as_index=False).mean()

SibSp  Survived
0      0  0.345395
1      1  0.535885
2      2  0.464286
3      3  0.250000
4      4  0.166667
5      5  0.000000
6      8  0.000000

In [237]:
# people with 1 number of siblings has more percentage of survival than with no or more number of siblings, whereas person with
# 5 and 8 number of siblings has 0 percentage of survival.

In [238]:
dataset[['Parch','Survived']].groupby('Parch',as_index=False).sum()

Parch  Survived
0      0       233
1      1        65
2      2        40
3      3         3
4      4         0
5      5         1
6      6         0

In [239]:
dataset[['Parch','Survived']].groupby('Parch',as_index=False).mean()

Parch  Survived
0      0  0.343658
1      1  0.550847
2      2  0.500000
3      3  0.600000
4      4  0.000000
5      5  0.200000
6      6  0.000000

In [240]:
# people with 1 number of children has more percentage of survival than with no or more number of siblings, whereas person with
# 5 number of children has 0 percentage of survival.

In [241]:
dataset.Fare.agg(['max','min','mean','median'])

max       512.329200
min         0.000000
mean       32.204208
median     14.454200
Name: Fare, dtype: float64

In [242]:
dataset[['Fare','Survived']].groupby('Fare',as_index=False).mean()

Fare  Survived
0      0.0000  0.066667
1      4.0125  0.000000
2      5.0000  0.000000
3      6.2375  0.000000
4      6.4375  0.000000
..        ...       ...
243  227.5250  0.750000
244  247.5208  0.500000
245  262.3750  1.000000
246  263.0000  0.500000
247  512.3292  1.000000

[248 rows x 2 columns]

In [243]:
dataset[['Embarked','Survived']].groupby('Embarked',as_index=False).sum()

Embarked  Survived
0        C        93
1        Q        30
2        S       217

In [244]:
dataset[['Embarked','Survived']].groupby('Embarked',as_index=False).mean()

Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.336957

In [245]:
# people from Port of Embarkation C has more percentage of survival than people Port of Embarkation Q and S. 

In [246]:
dataset[(dataset.Fare==0.0)&(dataset.Survived==0)]

PassengerId  Survived  Pclass                              Name   Sex  \
179          180         0       3               Leonard, Mr. Lionel  male   
263          264         0       1             Harrison, Mr. William  male   
277          278         0       2       Parkes, Mr. Francis "Frank"  male   
302          303         0       3   Johnson, Mr. William Cahoone Jr  male   
413          414         0       2    Cunningham, Mr. Alfred Fleming  male   
466          467         0       2             Campbell, Mr. William  male   
481          482         0       2  Frost, Mr. Anthony Wood "Archie"  male   
597          598         0       3               Johnson, Mr. Alfred  male   
633          634         0       1     Parr, Mr. William Henry Marsh  male   
674          675         0       2        Watson, Mr. Ennis Hastings  male   
732          733         0       2              Knight, Mr. Robert J  male   
806          807         0       1            Andrews, Mr. Thomas Jr  male   
815          816         0       1                  Fry, Mr. Richard  male   
822          823         0       1   Reuchlin, Jonkheer. John George  male   

      Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
179  36.0      0      0    LINE   0.0   NaN        S  
263  40.0      0      0  112059   0.0   B94        S  
277   NaN      0      0  239853   0.0   NaN        S  
302  19.0      0      0    LINE   0.0   NaN        S  
413   NaN      0      0  239853   0.0   NaN        S  
466   NaN      0      0  239853   0.0   NaN        S  
481   NaN      0      0  239854   0.0   NaN        S  
597  49.0      0      0    LINE   0.0   NaN        S  
633   NaN      0      0  112052   0.0   NaN        S  
674   NaN      0      0  239856   0.0   NaN        S  
732   NaN      0      0  239855   0.0   NaN        S  
806  39.0      0      0  112050   0.0   A36        S  
815   NaN      0      0  112058   0.0  B102        S  
822  38.0      0      0   19972   0.0   NaN        S

# Missing Values

In [247]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [248]:
dataset.Age.mean()

29.69911764705882

In [249]:
dataset.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [250]:
new_dataset = dataset.fillna({
    'Age':dataset.Age.mean(),
    'Cabin':'NaN',
    'Embarked':'S'
})

In [251]:
new_dataset.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Build a Model For Predictions

In [252]:
df1 = new_dataset[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [253]:
df1.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [254]:
df1.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [255]:
df2 = pd.get_dummies(df1[['Sex','Embarked']])

In [256]:
df2.head()

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0           0         1           0           0           1
1           1         0           1           0           0
2           1         0           0           0           1
3           1         0           0           0           1
4           0         1           0           0           1

In [257]:
df3 = df1.select_dtypes(exclude=['object'])    
df3.head()

Pclass   Age  SibSp  Parch     Fare
0       3  22.0      1      0   7.2500
1       1  38.0      1      0  71.2833
2       3  26.0      0      0   7.9250
3       1  35.0      1      0  53.1000
4       3  35.0      0      0   8.0500

In [258]:
final_dataset = pd.concat((df2,df3),axis=1)

In [259]:
final_dataset.head()

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  Pclass   Age  \
0           0         1           0           0           1       3  22.0   
1           1         0           1           0           0       1  38.0   
2           1         0           0           0           1       3  26.0   
3           1         0           0           0           1       1  35.0   
4           0         1           0           0           1       3  35.0   

   SibSp  Parch     Fare  
0      1      0   7.2500  
1      1      0  71.2833  
2      0      0   7.9250  
3      1      0  53.1000  
4      0      0   8.0500

In [260]:
x = final_dataset.values
y = dataset.Survived.values

In [261]:
from sklearn.preprocessing import StandardScaler
norm = StandardScaler()
norm.fit_transform(x)

array([[-0.73769513,  0.73769513, -0.48204268, ...,  0.43279337,
        -0.47367361, -0.50244517],
       [ 1.35557354, -1.35557354,  2.0745051 , ...,  0.43279337,
        -0.47367361,  0.78684529],
       [ 1.35557354, -1.35557354, -0.48204268, ..., -0.4745452 ,
        -0.47367361, -0.48885426],
       ...,
       [ 1.35557354, -1.35557354, -0.48204268, ...,  0.43279337,
         2.00893337, -0.17626324],
       [-0.73769513,  0.73769513,  2.0745051 , ..., -0.4745452 ,
        -0.47367361, -0.04438104],
       [-0.73769513,  0.73769513, -0.48204268, ..., -0.4745452 ,
        -0.47367361, -0.49237783]])

In [262]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.20, random_state = 1)

# Predictions

### Logistic Regression

In [263]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train,y_train)

C:\Users\asus\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [264]:
y_pred = log.predict(x_test)

In [265]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[90 16]
 [22 51]]


In [266]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)
print(acc)

0.7877094972067039


### Random Forest

In [267]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [268]:
y_pred = rf.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[94 12]
 [26 47]]


In [269]:
acc = accuracy_score(y_test,y_pred)
print(acc)

0.7877094972067039


### KNN Classification

In [270]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [271]:
y_pred = knn.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[90 16]
 [33 40]]


In [272]:
acc = accuracy_score(y_test,y_pred)
print(acc)

0.7262569832402235
